{% set name = "telluric" %}
{% set version = "0.13.11" %}
{% set sha256 = "12126153dd6290aa464619f83d44091a40322b3258b4ada464ed9a39c25bc828" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv '
  noarch: python

requirements:
  host:
    - python >=3.6
    - setuptools
    - versioneer-518
    - pip

  run:
    - python >=3.6
    - affine
    - fiona >=1.8.4,<2
    - folium >=0.6.0
    - ipyleaflet
    - shapely >=1.6.3,<2
    - rasterio >=1.2.0,<2
    - pillow
    - mercantile >=0.10.0
    - matplotlib-base
    - boltons
    - imageio
    - lxml

test:
  imports:
    - telluric

about:
  home: http://github.com/satellogic/telluric
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Interactive geospatial data manipulation in Python
  description: |
    telluric is a MIT licensed Python library to manage vector and raster
    geospatial data in an interactive and easy way. It lets you read the common
    vector and raster geospatial formats (leveraging on well known libraries
    such as fiona, shapely and rasterio) and makes it extremely easy to combine
    data sources with different projections, visualize them, read and write
    them from/to disk, and more.
  doc_url: http://telluric.readthedocs.io/
  dev_url: https://github.com/satellogic/telluric

extra:
  recipe-maintainers:
    - drnextgis
