travis:
  secure:
    BINSTAR_TOKEN: id9OpWfp47gOAStZyLKRU/RmcKHtJeeTbv3ZT04lEci0GzQIFij7v9BAmD8LDk9nHJExQHozjH4JYItB62I/9IthF2+wGHZDl3wKsBvBBfllKZZQ0yvRN7L2349KSsxUX/mK8iQJtn+JGB857mgDwDGN/XFWD0YxhL9Y0pgbZsmnkctMFYWvjzCGyciUd/QeTdSa72TGkv1fX4qBgJaW8Yo6Mm2uiLGN79+ldVqJR1cIdmHcaCQlM5D4Z60QZcWpXJ0LxGGbz85LVUb0QydlvsOOIKMWmmB91bIPSbgAQDEOtlbYFZkE03Qe6rSFnvjtPrW17Z6rdk3VSOu5A1rlJwjewIuj4Fn4MYSzbmtQXLUCUgFyRigIyXolwa9pAXiBsafbWkP+5pBa9oZk7PFOCh1p/zg/NK8xOfabm1dSvtUEEOM8yXmmsW9Z04uJtdZYoDsiDbgDah6wfMdbgohH0QqRf1+CUy/hUd7x2Nm0G4CbVcbjlbYLMrcii+Q95YKG1EK0ExMECrkor5xCZJDmBGWBsDCd58hN6ihNnvaqSVoJUVRk2FhxEFCdseKxny/Cb7rbvSgDD4tlBux2mi6EMtjYht95kKe3RKvyTXvxXkl5L/M2PGRhu3S8N4PFvXTqv24EdMNVhXJ/AI6OZLcVxXUloq3aMBe/ISf89FA6bRo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
